// src/app/api/chat/route.ts
import { NextRequest, NextResponse } from 'next/server';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { message } = body;

    // Validate input
    if (!message || typeof message !== 'string' || message.trim() === '') {
      return NextResponse.json(
        { error: 'Invalid input: "message" is required and must be a non-empty string.' },
        { status: 400 }
      );
    }

    // Get API key from environment variable
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      console.error('❌ GEMINI_API_KEY is missing in .env.local');
      return NextResponse.json(
        { error: 'Server configuration error. API key missing.' },
        { status: 500 }
      );
    }

    // ✅ Use the free-tier model: gemini-2.5-flash
    const url = `https://generativelanguage.googleapis.com/v1/models/gemini-2.5-flash:generateContent?key=${apiKey}`;

    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [
          {
            parts: [{ text: message }],
          },
        ],
        generationConfig: {
          temperature: 0.7,
          topK: 40,
          topP: 0.95,
          maxOutputTokens: 1024,
        },
      }),
    });

    // Read raw response text (only once!)
    const rawText = await response.text();
    console.log('✅ Raw Gemini API Response:', rawText);

    // Parse JSON safely
    let data;
    try {
      data = JSON.parse(rawText);
    } catch (parseError) {
      console.error('❌ Failed to parse JSON:', rawText);
      return NextResponse.json(
        { error: 'Invalid response format from AI service' },
        { status: 500 }
      );
    }

    // Handle API errors
    if (!response.ok) {
      const errorMsg = data.error?.message || 'Unknown error';
      console.error('❌ Gemini API Error:', errorMsg);
      return NextResponse.json(
        { error: errorMsg },
        { status: response.status }
      );
    }

    // Extract reply
    const botText = data.candidates[0]?.content?.parts[0]?.text;
    if (!botText) {
      console.error('❌ No reply from Gemini:', data);
      return NextResponse.json(
        { error: 'No response generated by AI' },
        { status: 500 }
      );
    }

    return NextResponse.json({ reply: botText });

  } catch (error) {
    console.error('🚨 Chat API Internal Error:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}
